alias c=clear
alias cd='z'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias cat='bat'
alias ls='eza --colour=always --icons=always --group-directories-first'
alias ll='eza -l --colour=always --icons=always --git --group-directories-first'
alias la='eza -la --colour=always --icons=always --git --group-directories-first'
alias py='python3'
