# Use custom format
format = '''
$git_branch$git_status$python$java$c$cpp$lua$package$rust$dotnet
$directory
$character '''

[c]
format = 'via [$name $version]($style)'

[cpp]
disabled = false
format = 'via [$name $version]($style)'

[cmd_duration]
disabled = true

[container]
format = '[$symbol \[$name\]]($style) '

[directory]
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

[dotnet]
symbol = '🥅 '
style = 'green'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = '🏳'
ahead = '🏎💨'
behind = '😰'
diverged = '😵'
up_to_date = '✓'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'

[java]
symbol = '🌟 '

[lua]
format = 'via [🌕 $version](bold blue) '

[python]
symbol = '👾 '
pyenv_version_name = true

[rust]
format = 'via [⚙️ $version](red bold)'

[sudo]
style = 'bold green'
symbol = '👩‍💻 '
disabled = false
